---
deployment:
  tasks:
    - export DEPLOYPATH=/home/regapikc/stephen.regapik.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R webfonts $DEPLOYPATH
